# Generated by Django 4.2.5 on 2023-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'member'), ('moderator', 'moderator')], default='member', max_length=9, null=True),
        ),
    ]
