# Generated by Django 4.2.5 on 2023-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_payments_amount_alter_payments_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
    ]
