# Generated by Django 4.2.5 on 2023-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='сумма оплаты'),
        ),
    ]
