# Generated by Django 4.2.5 on 2023-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_payments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=2000, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='цена'),
        ),
    ]
