# Generated by Django 4.2.5 on 2023-10-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_course_amount_alter_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
